project06/config/routes.rb
Gamez::Application.routes.draw do
  resources :users, :user_sessions, :games, :roles
  
  root :to => 'home#index'

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'register' => 'users#new', :as => :register
  
  namespace :admin do
    resources :users
    match 'me' => 'users#edit'
    resources :games
    resources :roles
    root :to => 'games#index'
  end

  namespace :member do
    resources :users, :only => [:edit, :update]
    match 'me' => 'users#edit', :as => :me
    resources :games
    root :to => 'games#index'
    
  end
end

project06/app/views/layouts/_atopbar.html.haml
.atopbar
  = link_to 'Games', admin_root_path
  = link_to 'Users', admin_users_path
  = link_to 'Roles', admin_roles_path

project06/app/views/layouts/_auserbar.html.haml
.topbar
  Hello
  = link_to current_user.full_name, edit_admin_user_path(current_user)
  , 
  = current_user.get_role.capitalize
  %br
  = link_to Admin, admin_root_url
  = link_to "Logout", :logout

project06/app/views/layouts/_muserbar.html.haml
.topbar
  Logged in as
  = link_to current_user.full_name, :member_me
  ,
  = current_user.get_role
  %br
  = link_to 'Games', member_games_path
  = link_to "Logout", :logout

project06/app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Gamez
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  = render :partial => 'layouts/auserbar'

  %h1
    = link_to "Gamez", root_url
    Admin
  %body
    = render :partial => 'layouts/atopbar'
    %br
    = yield

project06/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Gamez
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  .topbar
    - if current_user.nil?
      = link_to "Login", :login
      = link_to "Register", :register
    - elsif current_user.is_admin?
      = render :partial => 'layouts/auserbar'
    - else current_user.is_member?
      = render :partial => 'layouts/muserbar'
  %h1
    = link_to "Gamez", root_url
  
  - if !current_user.nil? and current_user.is_admin?
    = render :partial => 'layouts/auserbar'
  %body
    = yield

project06/app/views/layouts/member.html.haml
!!!
%html
  %head
    %title Gamez
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  = render :partial => 'layouts/muserbar'
    
  %h1
    = link_to "Gamez", root_url

  %body
    %br
    = yield